/*
 * DO NOT MODIFY.
 * This file was generated by ms_gen_mvxv_h.py
 */
#define MVXV_HEAD_VER   "4"
#define MVXV_LIB_TYPE   "##"
#define MVXV_CHIP_ID    "I2M#"
#define MVXV_CHANGELIST "ge7e5e6a53c"
#define MVXV_COMP_ID    "KL_LX409##"
#define MVXV_EXT        "[BR:ssd202d_miyoo-mini-plus_linux-4.9.84]"

